language: python
python:
  - "2.7"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt -e track/
script:
  - py.test track/tests/
after_success:
  - coveralls